server:
  port: 9005

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nicolbase
    username: root
    password: postgres
  data:
    redis:
      host: localhost
      port: 6379
      password:
      repositories:
        enabled: false
  thymeleaf:
    prefix: classpath:/templates/
  mail:
    host: <your_smtp_host>
    port: 587
    username: <your_username>
    password: <your_password>
    protocol: smtp
    properties:
      mail:
        debug: false
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
  messages:
    basename: lang/messages

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

management:
  health:
    mail:
      enabled: false

jimmer:
  language: kotlin

nicol:
  http-proxy:
    enabled: true
    host: 192.168.63.21
    port: 7890
  security:
    enabled: false
  mail:
    sender: Nicol
    topic: TOPIC:EMAIL
    callbackUrl: http://${server.port}/v1/verify-email
    subject: Welcome to Nicol
  mq:
    streams:
    - topic: ${nicol.mail.topic}
      groups:
      - name: GROUP:NORMAL
        callback: LOG
        consumers: CONSUMER-1
  verify:
    access-token-duration: 15m
    refresh-token-duration: 24h
    token-symmetric-key: 12345678901234567890123456789012
    footer: 'Project Nicol'
  inference:
    driver-mode: CPU
    model:
      check-point: model/stories15M.bin
    tokenizer:
      path: model/tokenizer.bin